[package]
name = "openfsdecrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
clap = { version="4.5.4", features = ["derive"] }
indicatif = "0.17.8"
windows-sys = { version = "0.52.0", features = ["Win32_Security_Cryptography", "Win32_System_Diagnostics_Debug"] }
